package com.homework.rewards.bo.impl;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.homework.rewards.bo.PurchaseBO;
import com.homework.rewards.dao.PurchaseRepository;
import com.homework.rewards.dto.PurchaseDTO;
import com.homework.rewards.model.Purchase;

@Component
public class PurchaseBOImpl implements PurchaseBO {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(PurchaseBOImpl.class);

	@Autowired
	private PurchaseRepository purchaseRepository;

	@Override
	public List<Purchase> getAll() {
		return purchaseRepository.findAll();
	}

	@Override
	public Optional<Purchase> findById(String purchaseId) {
		return purchaseRepository.findById(purchaseId);
	}
	
	@Override
	public Purchase create(final PurchaseDTO purchaseDTO) {
		final Integer points = calculatePoints(purchaseDTO.getTotalSpent());
		LOGGER.info("A total of {} points calculated from the total purchase of {} for the user {}", points,
				purchaseDTO.getTotalSpent(), purchaseDTO.getCustomerId());

		final Purchase purchase = new Purchase(null, purchaseDTO.getTotalSpent(), points, purchaseDTO.getCustomerId(), purchaseDTO.getTimestamp());

		return purchaseRepository.save(purchase);
	}

	@Override
	public Optional<Purchase> update(PurchaseDTO purchaseDTO) {
		Optional<Purchase> optional = purchaseRepository.findById(purchaseDTO.getTransactionId());

		if (!optional.isPresent()) {
			return optional;
		}

		final Integer points = calculatePoints(purchaseDTO.getTotalSpent());
		Purchase purchase = new Purchase(optional.get().getTransactionId(), purchaseDTO.getTotalSpent(), points,
				optional.get().getCustomerId(), purchaseDTO.getTimestamp());
		
		return Optional.of(purchaseRepository.save(purchase));
	}

	@Override
	public boolean delete(final String transactionId) {
		if (!purchaseRepository.existsById(transactionId)) {
			return false;
		}
		purchaseRepository.deleteById(transactionId);
		return true;
	}

	/**
	 * Given the total Spent calculates the points generated by the purchase
	 * 
	 * Example:
	 *  A customer receives 2 points for every dollar spent over $100 in each transaction, plus 1 point
	 *  for every dollar spent over $50 in each transaction
	 *  (e.g. a $120 purchase = 2x$20 + 1x$50 = 90 points).
	 *  
	 * @param totalSpent
	 * @return
	 */
	private Integer calculatePoints(final Float totalSpent) {
		final Integer total = totalSpent.intValue();

		final Integer points = (total > 100) ? 2 * total - 150 : (total > 50) ? total - 50 : 0;
		return points;
	}

}
